-- MySQL Script generated by MySQL Workbench
-- Mon Oct  2 18:06:09 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema heroku_29a5bece3680a55
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema heroku_29a5bece3680a55
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `heroku_29a5bece3680a55` DEFAULT CHARACTER SET utf8 ;
USE `heroku_29a5bece3680a55` ;

-- -----------------------------------------------------
-- Table `heroku_29a5bece3680a55`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_29a5bece3680a55`.`products` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `manufacturer` VARCHAR(45) NULL DEFAULT NULL,
  `cost` DECIMAL(8,2) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT 'this is a some product',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `heroku_29a5bece3680a55`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_29a5bece3680a55`.`users` (
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `registration_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `role` VARCHAR(45) NULL DEFAULT 'USER',
  PRIMARY KEY (`login`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
